### ISSUE TITLE
Integrity Error while importing old data in trade dangerous

### ISSUE THREAD

**Issue by tdroenner** [Ayexor/MathSem_Presentation#1]
Issue reporting on trade dangerous didn't work. Trying to report here. Using TDHelper to create new database:

Command line:  import -P eddblink -O all
NOTE: Rebuilding cache file: this may take a few moments.
NOTE: Missing "D:\TDHelper\data\TradeDangerous.prices" file - no price data.
NOTE: Checking for update to 'modules.json'.
NOTE: Processing Upgrades: Start time = 2024-01-03 00:16:08.121620
NOTE: Finished processing Upgrades. End time = 2024-01-03 00:16:08.127620
NOTE: Checking for update to 'index.json'.
NOTE: Processing Ships: Start time = 2024-01-03 00:16:08.141623
NOTE: Finished processing Ships. End time = 2024-01-03 00:16:08.145621
NOTE: Checking for update to 'systems_populated.jsonl'.
NOTE: Processing Systems: Start time = 2024-01-03 00:16:08.319622

                                                           
NOTE: Finished processing Systems. End time = 2024-01-03 00:16:08.769710
NOTE: Checking for update to 'stations.jsonl'.
NOTE: Processing Stations, this may take a bit: Start time = 2024-01-03 00:16:08.951702
NOTE: Simultaneously processing ShipVendors.
NOTE: Simultaneously processing UpgradeVendors, this will take quite a while.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\trade.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\trade.py", line 40, in main
    cli.main(sys.argv)
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\cli.py", line 70, in main
    trade(argv)
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\cli.py", line 125, in trade
    results = cmdenv.run(tdb)
              ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\commands\commandenv.py", line 84, in run
    return self._cmd.run(results, self, tdb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\commands\import_cmd.py", line 126, in run
    if not plugin.run():
           ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\plugins\eddblink_plug.py", line 1098, in run
    self.importStations()
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\plugins\eddblink_plug.py", line 523, in importStations
    self.execute("""INSERT INTO System
  File "C:\Program Files\Python312\Lib\site-packages\tradedangerous\plugins\eddblink_plug.py", line 120, in execute
    result = cur.execute(sql_cmd, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: System.name

Command completed.

**Comment by Ayexor** [comment]
Activated issues and created @https://github.com/Ayexor/Trade-Dangerous/issues/1.
